sudo: false
language: generic
env:
  global:
    - secure: "SV6aoQCl4bbIoWlK40HVO2GGSpFTE4iq34BeGhVtRa3a4PdNOHe96o+g7rJQdcYQLUD8mtH2Tb2SOqQbP01BITKoxqHmvGNtitUiLoHqAEBtbcswMt5yxh87x6xdgzZMiw5jCFzqJ9ZvacVIumZ1tcZd+HppF6O53tDbp5ABaruTxNwAy+03hSaI2D2BTgDkBbKWPmnS3Q//f0rKKgmGiATXnTN3jxIqb0yI8DbmaRvXHAL/340JfBYJZSwswO8uDZ0Fb0Weg7+GTeZ6SzwskrE9O6+jqhAEbaoeS0VPB+CA1LfPfKb3tyzsDewpaLvneW3bFt/e6V+KWYUiiMBVvoqW3Dq6ix1Fv2TgnkILjoxtOW+B7YT5l5JC2YQh/rM89nw6yOwLfumMrfEbcX5e7c9LE85yiewEg7MyNk5730wgfY9DfQh7qqmGD5PygXIVvEXLJgy89rde6ppG7TjLo81xFcF3upAEz4EaD8veNMJYrdy2tKk/dBAjMe/87MZbO8fUn7B9PJCNhaX8IGsmoFFiytxc3lb2bovl1nTxESYNJvHHaWLCY/q8i8FIhoTBbm26nFgAtnGtvudS6Lku8xFbjKSgrqMfKYH9WPUlPMozf1wuRGoo8c1auYnudN0OiUKCrbGv3HkWHl1YmDSz3cG8cBWPHSp+ge87FvtzEKw="
    - PROJECT_NAME=hello_world

matrix:
  include:
    - os: linux
      env: >
        TARGET=x86_64-unknown-linux-gnu
        PLATFORM=linux-x64

    - os: osx
      env: >
        TARGET=x86_64-apple-darwin
        PLATFORM=osx-x64

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cargo

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - export VERSION=$(git log -1 | grep -i "version change to" | sed "s/.*[vV]ersion change to v\{0,1\}//")

install:
  - ./ci/travis/install.sh

script:
  - ./ci/travis/script.sh

before_deploy:
  - ./ci/travis/before_deploy.sh

# Deploy happens only when pushing a tag and only for stable rust.
deploy:
  provider: releases
  api_key:
    secure: "siZOf8NjAdDKNWRTXN2KN76GAcvVGZ2+qm2zeSX0ePTQFtoMhB15Z52NSDVipSW81WZQ0/h8DxiHk/U+vKeAth33Q5zudk/o5hBSlfauZh2VicvweQmVBm1pIQQsPtkE7LJy2Uqhw+B9+KFrYGT3kgBo6fzXSxTeY13L8wPs7vT/LuB7J7OR2zAmGoK1IgYFwahlooXCY0G48x5sAs72yMb5Nx5DjaiGb8mSIYOQgWYRJL7gCfkDxKikzP9jvL4gTNHHYYfWjnxR089fIBCk9Mlbkich4s+tUe32M5Yd8dl1lCeAc0VHKeoSLFLNapqN/JNaSjcJ2Sd7o7hYOIFD1qL19TKE0duuy4yoPjXwXawpjAE96+4GpC/rfCGZCLQ/h4tWW3NfIEAlmyn7xops9e2EEkb0e4QwNhRnb1arXQxcBJRp1SnIL0ylhxFRbw8f5mDXWJrd7F7HOdCypseK/nYRLwwmMhGchYwDf0IE+5hg6uKWk2Ewf0AjtjGoywz58iynCprYh0AG0kfQrSU8KJUyrTLgGIOg9h8NmlOZoOSqIKVZY+0HKfIFP/XWlpES5rAgEpDp1KZkbe8jdbjLy2xS4AT+VNId8tBEYB17vgHvjK8LcvJU88h+iJWU5KMEMOow+P3Wa+3SD718ajyeaaPbmkkZLUTR1v29X+RF9C4="
  file: ${PROJECT_NAME}-v${VERSION}-${PLATFORM}.tar.gz
  skip_cleanup: true
  draft: true
  tag_name: v${VERSION}
  on:
      condition: ("${CHANNEL:-stable}"=stable) && (-n "$VERSION")

notifications:
  email: never